### ISSUE TITLE
dangling comma

### ISSUE THREAD

**Issue by jpriebe** [sqville/sqv#1]
When I ran generate.py, I got the following error:

> Illegal dangling comma in map (pos (397, 4))
> File: /Users/priebe/git/diesel/source/diesel/pubtools2/qooxdoo-5.0.1-sdk/application/sqv/source/class/sqv/theme/clean/Image.js

Fixed it by removing this comma in Image.js:

```
            "html" : {
              "border-radius": ".0625em",
            },
```

**Comment by sqville** [comment]
Hi Jason and thanks for the note!

Was it on the "fileicon-dy" entry within the CSSICONS object? I just searched my code, and i'm not seeing the same thing. Plus i've been away from this project for a while so no telling where i left off on all this :-)

**Comment by sqville** [comment]
Jason, I see what I did now. A few months back I decided to fork qooxdoo, and make clean a "real theme." I split out the theme from my little demo theme app, and left a lot undone in this repo. The latest theme without my controls (Diagram and Upload) is in my sqville-qooxdoo fork, clean_theme_v01 branch. Apologies for that, and thanks again for the note.

**Comment by jpriebe** [comment]
Thanks for taking at look at this!  I'll try the clean_theme_v01 code.  I'm
excited to put a new "paint job" on a very old qooxdoo app (12 years and
going strong!)

**Comment by jpriebe** [comment]
OK -- I see what you're doing with the Clean theme, but I'm not sure how I
would use it until it is accepted into the main qooxdoo repo.  I could pull
down your fork, but if the theme never gets added to the main repo, I will
have to manually port your theme to newer qooxdoo versions, right?

Maybe I'm missing something, but it doesn't seem like the theme system
lends itself to a nice standalone theme package that can be easily added to
a qooxdoo-based app.

**Comment by sqville** [comment]
I wish I was better at the Devops/builds side of life Jason, because then I would have a definitive, almost condescending sounding answer for you ;-)
What i do have is a thought. What if you fork qooxdoo (like i have), merge sqville/qooxdoo -master, then, going forward, merge both qooxdoo/qooxdoo AND my forked master into your fork? I've done this across branches. Not sure if it would work across repos. If this is a real thing then it should take care of you until I get my act together. What do you think?

**Comment by jpriebe** [comment]
That might work.  But I will be honest, I have built a pretty solid proof
of concept with the sqv theme that I originally downloaded.  And that's
quite a bit more modular, so I may stick with that.  Laziness being a
virtue and all... :-)

**Comment by sqville** [comment]
Hey Jason,

I just made some massive updates to my theme: http://sqville.com/examples/widgetbrowser2018/index.html
It's all sitting in my forked version of qooxdoo. I'll be submitting the PR to the group this week. Not sure how long it's going to take to get it there, but happy to help you tee up a version for your app if needed.  Just let me know.

**Comment by jpriebe** [comment]
Sweet!  I'm dozens of hours into reskinning our app (the new theme uses
much larger geometries, so even our best-designed interfaces need a lot of
reworking, and some of our worst ones had lots of hard-coded geometries,
and have to be rebuilt).  I'm excited that you've submitted a pull
request.  Our app looks so much fresher with your theme; I hope they'll
accept the PR, and that it will help with qooxdoo adoption.

When I finish this work, I will give your theme a shot.  Thanks for all the
hard work I know you've put into this theme!

**Comment by sqville** [comment]
That resizing is a bear! I helped Tartan Solutions redesign their cloud product and, no joke, the majority of my time was spent ripping out Canvas layouts and replacing with VBox and HBoxes. They too were sucked in by the awesomness that was the Canvas layout, back in the day :-)

Update on the PR. The core team doesn't want to take responsibility for the theme. I don't blame them. My theme, on the surface, looks complex. But, in reality, it isn't. Everything I put in there follows tenants set forth by the framework itself.  If I chopped up this one big PR into little PRs, asking for property and state additions here and there, then they would all probably go through without too much fuss.

Anyway, I'm not complaining. No one likes extra work and responsibility dropped on them by people with good intentions. It's like getting a puppy as a gift when you didn't want one. I'll keep you posted on the contrib.

Last thing. When you get a sec, take a look at your app(s) then take a look at semantic-ui.com (for inspiration). Then let me know your top 3 - 5 controls that you would like variations of. CheckBox is an example. Qooxdoo has one. Semantic UI has two, the standard checkbox and the one that looks like a slider. If I had more real world use cases then my time spent would be that much more focused and beneficial to everyone. :-)

**Comment by jpriebe** [comment]
I also went with VBox and HBox.  Especially once I started following the
Bootstrap UI convention of putting field labels *above* the field instead
of next to the field, it just made more sense to flow the UI down the
screen.  Plus, it has the awesome benefit of reflowing when you set
visibility to "excluded" on a control.  I was able to remove large numbers
of fixed height and width specifiers, which will presumably help code
maintenance.

I don't know if I specifically need any alternate versions of controls, but
I can tell you where I've run into some trouble.

Forgive me if (a) you've already fixed these or (b) the problems I had were
due to interference between sqv/clean/*.js and my app's theme files (I have
some custom controls, so I had to carry over my theme files to the newly
skinned version of the app, making adjustments as I worked my way through
the app's UI).  So these issues may or may not apply to a "pure" sqv/clean
app implementation.  I'm a complete hack when it comes to the themes.  I
know qooxdoo pretty well (been building apps in it for 13 years), but I
barely understand how the themes work.

- Table row heights were still kind of small; I changed the height of them,
but then I had text alignment problems (all the text was top-aligned).  I
had to override all the renderers to add some padding

- ToggleButton - the toggle state is very subtle visually

- Selection colors - I think the default selection color is very subtle.
It's aesthetically pleasing, but has some usability issues

- Icons - I love the idea of using fonts and SVG.  But I really needed my
own icons, and I am lazy, so I just wanted to use PNGs like I always had
(but adding @2x versions), so I removed a lot of the directives that your
docs suggest putting into the Application.js.  I kind of had to hack my way
through that.  I wish the theme and the fonts+SVG support were a little
more modular.

I think rather than going overboard with alternate versions of controls,
maybe you spend your time working on the packaging / documentation / etc.
to make implementation as painless as possible (of course, if you have time
to do both things, go for it!).  Get some momentum behind your theme -- I
think it will be very well received by qx developers.  Maybe there will be
enough pressure that the team incorporates your theme officially.

**Comment by sqville** [comment]
Sounds like you and I had the exact same experience. I'm about to try my hand at using the Flow layout as the basis for single source app (one code base for all screens and devices). I'll let you know how that goes. :-)

I really appreciate you sharing your insight Jason! Super helpful!

- Table - This guy is a bear to theme too. As a matter of fact it's more coding than themeing because you have to create your own Cell and Row renderer classes in order to get the precision you want/need. This is on my to-do list to rein in.
- Subtle Colors - I completely agree with you on this. I did darken a bit, but it needs more. I will put more time into this for sure.
- Icons - **Fonts**, I am defaulting to the framework team. They have a competing implementation that gets to the same result. I will revisit if/when necessary. **SVG**, embedding SVG into code is a must, and becoming common practice among frameworks. **Pure CSS Icons**, after HTML, nothing is more native than CSS. If done correctly, and creatively, it could be a significant "differentiator", and bring some notoriety. So "worth a try" in my book :-)

Happy holidays and thanks again!

**Comment by jpriebe** [comment]
I may have found a little glitch in the menubutton icons.

I set a 24x24 icon on a menubutton.  I noticed things looked a little
strange, and when I inspected the DOM, that element was an <img> tag with a
src value *and* a backgroundImage.  So it was doubling up my images.

I modified the menu-button/icon appearance in my app's theme to override
your 18x18 icons with 24x24, and I set scale=false.  That seems to have
fixed the problem.  Now I get a <div> with a background image.

At first I thought that maybe using high-res images (@2x) was to blame, but
I don't think that's the issue.  I think it's the scale=true setting in
menu-button/icon.  Maybe you can have a look at that.

**Comment by sqville** [comment]
Hmm. That looks to be carry over from some testing i was doing a long time back. I say that because the only inappropriate place i have scale=true in my latest and greatest repo is on my "primary-button/icon" appearance entry. I say "inappropriate place" because i do hard code sizes with scale for my SVG icons like tree folder and tree file. And my CSS icons like checkbox/icon. All others I've reverted back to the original qx way of handling "appearance-entry"/icon.

Anyway, sounds like you fixed it perfectly - setting scale back to false. Setting scale to true does flip the object's mode, thus changing the tag from div to image.

**Comment by sqville** [comment]
Jason, I just updated my sqv repo with the updates from the PR i sent to the qx team. This should have all the fixes I've done to date.

**Comment by sqville** [comment]
O, and do you mind if i close this issue? You can always open an new issue or email me directly - chris.eskew@sqville.com
